### ISSUE TITLE
Discord channel can't join

### ISSUE THREAD

**Issue by alvinonmars** [BookmapAPI/python-api#18]
Is it abandoned?
Are there any other discord channel?
Thanks

**Comment by alvinonmars** [comment]
The discord channel in readme is wrong.

I found the right one in https://bookmap.com/knowledgebase/docs/KB-Welcome

**Comment by rok-povsic** [comment]
@alvinonmars You probably mean the links in the Quick Guide document, right? I've updated them to a generic invitation link. Thank you for the notice!
