### ISSUE TITLE
get_sum typo error

### ISSUE THREAD

**Issue by IperGiove** [BookmapAPI/python-api#3]
Hi,
It would be nice to have the source code as a really open project, or at least the protocol/abstract of the library.
However I think there is a typo error:
#### get_sum
```
[...]
Note that a certain price level will be taken into account even if it has a zero size level. For
example, if `levels_num` is 2, and best bid is at price level 100 of size level 1, 99 is empty,
the method will count compute `1 + 0` and return `0`.
```
Maybe It should be: 
```
`1 + 0` and return `1`.
```

**Comment by nyckyta** [comment]
Hello. 

Regarding typo, you are right, it should be one, we will fix. Feel free to suggest similar changes via Pull Requests as well, we are happy to any support :)

As for making the project open source, we have to discuss it with management.

For now I will close this.
